version: '3'

volumes:
  whatsappData:
    driver: local
  whatsappMedia:
    driver: local

services:
  wacore:
    image: docker.whatsapp.biz/coreapp:v2.19.7
    restart: unless-stopped
    command: ["/opt/whatsapp/bin/wait_on_mysql.sh", "/opt/whatsapp/bin/launch_within_docker.sh"]
    ports:
      - "6250-6253:6250-6253"
    volumes:
     - whatsappData:/usr/local/waent/data
     - whatsappMedia:/usr/local/wamedia
    env_file:
      - db.env
    environment:
      WA_APP_MULTICONNECT: 1
      # Needs to reflect ports exposed above
      COREAPP_EXTERNAL_PORTS: "6250,6251,6252,6253"
      # $EXTERNAL_HOSTNAME should reflect the current machine's hostname
      # accessible to other containers
      COREAPP_HOSTNAME: "${EXTERNAL_HOSTNAME:?$EXTERNAL_HOSTNAME should reflect the current machine's hostname accessible to other containers}"
