version: '3'

volumes:
  whatsappData:
    driver: local
  whatsappMedia:
    driver: local

services:
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
  waweb:
    image: docker.whatsapp.biz/web:v2.19.7
    command: ["/opt/whatsapp/bin/wait_on_mysql.sh", "/opt/whatsapp/bin/launch_within_docker.sh"]
    ports:
     - "9090:443"
    volumes:
     - whatsappData:/usr/local/waent/data
     - whatsappMedia:/usr/local/wamedia
    env_file:
      - db.env
    environment:
      WA_APP_MULTICONNECT: 1
      WEBAPP_EXTERNAL_PORTS: "9090"
      WEBAPP_HOSTNAME: "waweb"
    depends_on:
      - "db"
  master:
    image: docker.whatsapp.biz/coreapp:v2.19.7
    restart: unless-stopped
    command: ["/opt/whatsapp/bin/wait_on_mysql.sh", "/opt/whatsapp/bin/launch_within_docker.sh"]
    ports:
      - "6250-6253"
    volumes:
     - whatsappData:/usr/local/waent/data
     - whatsappMedia:/usr/local/wamedia
    env_file:
      - db.env
    environment:
      WA_APP_MULTICONNECT: 1
      WA_MASTER_NODE: 1
      COREAPP_EXTERNAL_PORTS: "6250,6251,6252,6253"
      COREAPP_HOSTNAME: "master"
    depends_on:
      - "db"
      - "waweb"
  wacore:
    image: docker.whatsapp.biz/coreapp:v2.19.7
    restart: unless-stopped
    command: ["/opt/whatsapp/bin/wait_on_mysql.sh", "/opt/whatsapp/bin/launch_within_docker.sh"]
    ports:
      - "6250-6253"
    volumes:
     - whatsappData:/usr/local/waent/data
     - whatsappMedia:/usr/local/wamedia
    env_file:
      - db.env
    environment:
      WA_APP_MULTICONNECT: 1
      COREAPP_EXTERNAL_PORTS: "6250,6251,6252,6253"
      COREAPP_HOSTNAME: "wacore"
    depends_on:
      - "db"
      - "master"
